global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-posts'
    static_configs:
      - targets: ['host.docker.internal:80']  # Tu app Go 
    metrics_path: '/metrics'
    scrape_interval: 5s