# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  dev:
    cmds:
      - air
    silent: true
  test:
    cmds:
      - go test ./...
      - golangci-lint run
    silent: true