{
 "title": "Posts Service",
 "panels": [
  {
   "title": "Service Request Count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "increase(api_posts_service_request_count{job=\"go-posts\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Service Request Latency (avg ms by method)",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 10, "w": 24, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum by (method) (rate(api_posts_service_request_latency_microseconds_sum{job=\"go-posts\"}[5m])) / sum by (method) (rate(api_posts_service_request_latency_microseconds_count{job=\"go-posts\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Service Request Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "(sum by (method) (rate(api_posts_service_request_latency_microseconds_sum{job=\"go-posts\"}[20m])) / sum by (method) (rate(api_posts_service_request_latency_microseconds_count{job=\"go-posts\"}[20m])))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}