// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_all_dynamit.sql

package database

import (
	"context"
)

const listPosts = `-- name: ListPosts :many
SELECT id, title, content, created_at, updated_at
FROM posts
WHERE 
  ($1 IS NULL OR title = $1)
  AND
  ($2 IS NULL OR content = $2)
`

type ListPostsParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
