// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts_update.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET title = $2, content = $3
WHERE id = $1
`

type UpdatePostParams struct {
	ID      uuid.UUID
	Title   string
	Content string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost, arg.ID, arg.Title, arg.Content)
	return err
}
