// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts_insert.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertPost = `-- name: InsertPost :one
INSERT INTO posts (title, content) VALUES ($1, $2) RETURNING id
`

type InsertPostParams struct {
	Title   string
	Content string
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertPost, arg.Title, arg.Content)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
